name: stl
description: Supercharge Dart & Flutter with C++ STL architecture. Unlock zero-cost primitives, associative collections, memory views, and C++23 ranges.
version: 0.6.1
repository: https://github.com/jedizlapulga/stl

environment:
  sdk: ^3.11.3

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
