import 'dart:math';

/// A core abstract interface for deterministic random number engines.
///
/// Engines are responsible for producing a uniformly distributed stream
/// of pseudo-random integers. They mimic C++11's `UniformRandomBitGenerator`
/// and specific engine concepts.
abstract class RandomEngine {
  /// Creates a [RandomEngine].
  const RandomEngine();

  /// The minimum value potentially generated by this engine.
  int get min;

  /// The maximum value potentially generated by this engine (inclusive).
  int get max;

  /// Re-seeds the engine's internal state.
  void seed(int value);

  /// Generates and returns the next random integer.
  int next();

  /// Advances the engine's internal state by [count] steps, discarding the values.
  void discard(int count) {
    if (count < 0) {
      throw ArgumentError('Discard count cannot be negative.');
    }
    for (int i = 0; i < count; i++) {
      next();
    }
  }
}

/// A Linear Congruential Generator (LCG) engine.
///
/// Implements the formula: `x = (multiplier * x + increment) % modulus`.
/// By default, provides the parameters for C++'s `std::minstd_rand`.
class LinearCongruentialEngine extends RandomEngine {
  /// The multiplication constant used to generate the next state.
  final int multiplier;

  /// The increment constant added to the state.
  final int increment;

  /// The modulus constant defining the maximum range limit.
  final int modulus;
  int _state;

  /// Constructs a Linear Congruential Engine with custom parameters.
  LinearCongruentialEngine({
    required this.multiplier,
    required this.increment,
    required this.modulus,
    int initialSeed = 1,
  }) : _state = 0 {
    seed(initialSeed);
  }

  /// Factory mimicking `std::minstd_rand` (multiplier = 48271, mod = 2147483647).
  factory LinearCongruentialEngine.minstd([int seedValue = 1]) {
    return LinearCongruentialEngine(
      multiplier: 48271,
      increment: 0,
      modulus: 2147483647,
      initialSeed: seedValue,
    );
  }

  /// Factory mimicking `std::minstd_rand0` (multiplier = 16807, mod = 2147483647).
  factory LinearCongruentialEngine.minstd0([int seedValue = 1]) {
    return LinearCongruentialEngine(
      multiplier: 16807,
      increment: 0,
      modulus: 2147483647,
      initialSeed: seedValue,
    );
  }

  @override
  int get min => increment == 0 ? 1 : 0;

  @override
  int get max => modulus - 1;

  @override
  void seed(int value) {
    _state = value % modulus;
    if (_state == 0 && increment == 0) {
      _state = 1; // Prevent getting stuck at zero
    }
  }

  @override
  int next() {
    // We use modulo arithmetic directly. Note that if modulus is large,
    // multiplier * _state might exceed 53-bit JS safe integer limits.
    // For minstd_rand, 48271 * 2147483647 = ~1.03e14, which fits safely within 53 bits (9.0e15).
    _state = (multiplier * _state + increment) % modulus;
    return _state;
  }
}

/// A Mersenne Twister Engine (MT19937).
///
/// Provides a massive period of 2^19937 - 1 and high statistical quality.
/// Mimics C++'s `std::mt19937`. Operates fundamentally on 32-bit integers.
class MersenneTwisterEngine extends RandomEngine {
  static const int _n = 624;
  static const int _m = 397;
  static const int _matrixA = 0x9908b0df;
  static const int _upperMask = 0x80000000;
  static const int _lowerMask = 0x7fffffff;

  final List<int> _mt = List<int>.filled(_n, 0);
  int _mti = _n + 1;

  /// Constructs an MT19937 engine seeded with the given value.
  /// Standard default seed for mt19937 is 5489.
  MersenneTwisterEngine([int initialSeed = 5489]) {
    seed(initialSeed);
  }

  @override
  int get min => 0;

  @override
  int get max => 0xFFFFFFFF;

  @override
  void seed(int value) {
    _mt[0] = value & 0xFFFFFFFF;
    for (_mti = 1; _mti < _n; _mti++) {
      int prev = _mt[_mti - 1];
      int temp = 1812433253 * (prev ^ (prev >> 30)) + _mti;
      // Keep strictly to 32 bits
      _mt[_mti] = temp & 0xFFFFFFFF;
    }
  }

  @override
  int next() {
    int y;
    const List<int> mag01 = [0, _matrixA];

    if (_mti >= _n) {
      // Generate _n words at one time
      int kk;

      // Auto-seed if not initialized
      if (_mti == _n + 1) {
        seed(5489);
      }

      for (kk = 0; kk < _n - _m; kk++) {
        y = (_mt[kk] & _upperMask) | (_mt[kk + 1] & _lowerMask);
        _mt[kk] = _mt[kk + _m] ^ (y >>> 1) ^ mag01[y & 0x1];
      }
      for (; kk < _n - 1; kk++) {
        y = (_mt[kk] & _upperMask) | (_mt[kk + 1] & _lowerMask);
        _mt[kk] = _mt[kk + (_m - _n)] ^ (y >>> 1) ^ mag01[y & 0x1];
      }
      y = (_mt[_n - 1] & _upperMask) | (_mt[0] & _lowerMask);
      _mt[_n - 1] = _mt[_m - 1] ^ (y >>> 1) ^ mag01[y & 0x1];

      _mti = 0;
    }

    y = _mt[_mti++];

    // Tempering
    y ^= (y >> 11);
    y ^= (y << 7) & 0x9d2c5680;
    y ^= (y << 15) & 0xefc60000;
    y ^= (y >> 18);

    return y >>> 0; // Ensure unsigned 32-bit representation (important for web)
  }
}

/// A fast fallback pseudo-random engine delegating to Dart's native `dart:math` Random.
///
/// Useful when the overhead of software MT19937 or LCG is not desired,
/// but you still want the `RandomEngine` interface to pass into Distributions.
class DartNativeEngine extends RandomEngine {
  late Random _random;

  /// Constructs a native engine.
  DartNativeEngine([int? initialSeed]) {
    _random = initialSeed != null ? Random(initialSeed) : Random();
  }

  @override
  int get min => 0;

  @override
  int get max => 0xFFFFFFFF; // dart:math Random generates up to 2^32 natively

  @override
  void seed(int value) {
    _random = Random(value);
  }

  @override
  int next() {
    return _random.nextInt(0x100000000); // Generate up to 2^32 - 1
  }
}
